language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install python-coveralls
  - python setup.py install
script:
  - coverage run --source boardgamegeek -m py.test 
after_success:
  - coveralls
